version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
      - image: circleci/mongo:3.6.3

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # linting should be enacted to see if the code is following standards
      # local linting only runs on staged files, so things could slip through
      - run: npm run check-linting
      # run those tests ayyy
      - run: npm test

  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a0:6b:6c:68:25:51:03:c5:9d:a2:4c:22:ff:0b:77:bd"
      - checkout
      - run:
          name: Add Dokku to known_hosts
          command: |
            ssh-keyscan -H 134.209.93.116 >> ~/.ssh/known_hosts
            ssh-keyscan -H stacket.io >> ~/.ssh/known_hosts
      - run:
          name: Deploy to Dokku
          command: git push -f dokku@stacket.io:api master

workflows:
  version: 2

  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
