version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
      - image: circleci/mongo:3.6.3

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test

      deploy:
        docker:
          - image: buildpack-deps:trusty
        steps:
          # - add_ssh_keys:
          #     fingerprints:
          #       - "5a:b6:f5:b3:d8:92:b0:c2:e1:ac:8d:d6:ed:90:42:e0"
          - checkout
          - run:
              name: Add Dokku to known_hosts
              command: |
                ssh-keygen -R 134.209.93.116
                ssh-keygen -R api.stacket.io
                ssh-keyscan -H 134.209.93.116 >> ~/.ssh/known_hosts
                ssh-keyscan -H api.stacket.io >> ~/.ssh/known_hosts
          - run:
              name: Deploy to Dokku
              command: git push -f dokku@stacket.io:api master

workflows:
  version: 2

  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
